name: Anth

on: 
    push:
        branches:
            - master
    schedule:
        # run every Monday at 6am UTC
        - cron: '0 6 * * 1'

env:
  SETUP_XVFB: True  # avoid issues if mpl tries to open a GUI window
  TOXARGS: '-v'
  HYPOTHESIS_PROFILE: 'ci'

jobs:
    pip-env:
        name: ${{ matrix.os }}, Python ${{ matrix.python }}
        runs-on: ${{ matrix.os }}
        if: "!(contains(github.event.head_commit.message, '[skip ci]') || contains(github.event.head_commit.message, '[ci skip]'))"
        strategy:
            fail-fast: false
            matrix:
                python: ['3.10'] # ['3.8', '3.9', '3.10', '3.11']
                os: [ubuntu-latest] #, macos-latest] #[ubuntu-latest, ubuntu-20.04, macos-13, macos-12, macos-11]
        steps:
        - name: Check out repository
          uses: actions/checkout@v3
        - name: Set up Python ${{ matrix.python }}
          uses: actions/setup-python@v3
          with:
            python-version: ${{ matrix.python }}
        - name: Install base dependencies
          run: pwd && python -m pip install --upgrade pip pandas && python -m pip install .
        - name: 'Authenticate to Google Cloud'
          uses: 'google-github-actions/auth@v1'
          with:
            service_account: ${{secrets.SERVICE_ACCT}}
            credentials_json: '${{ secrets.ARCHSHEETKEY }}'
            create_credentials_file: True
        - name: "Install Google API Dependencies"
          run: python -m pip install gspread gspread-dataframe google pydrive
        - name: Run test
          run: python validation/architecture.py

